ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM*

ARDUINO_LIBS = aikocustom ArduinoJson

include /usr/share/arduino/Arduino.mk

